const data = [
    {
      planet: "Mercúrio",
      description: "Mercúrio é o menor planeta do Sistema Solar e o mais próximo do Sol. Sua órbita ao redor do Sol leva 87,97 dias terrestres, o menor de todos os planetas do Sol. Mercúrio é um dos quatro planetas terrestres do Sistema Solar e é um corpo rochoso como a Terra.",
      source: "https://pt.wikipedia.org/wiki/Merc%C3%BArio_(planeta)",
      overview: "images/mercury/planet-mercury.svg",
      internalStructure: "images/mercury/planet-mercury-internal.svg",
      surfaceGeology: "images/mercury/geology-mercury.png",
      rotationTime: "58.6 dias",
      revolutionTime: "87.97 dias",
      radius: "2.439,7 KM",
      averageTemperature: "430°C",
    },
  
    {
      planet: "Vênus",
      description: "Vênus é o segundo planeta a partir do Sol. É nomeado em homenagem a deusa romana do amor e da beleza. Como o objeto natural mais brilhante no céu noturno da Terra depois da Lua, Vênus pode lançar sombras e pode ser, em raras ocasiões, visível a olho nu em plena luz do dia.",
      source: "https://pt.wikipedia.org/wiki/V%C3%A9nus_(planeta)",
      overview: "images/venus/planet-venus.svg",
      internalStructure: "images/venus/planet-venus-internal.svg",
      surfaceGeology: "images/venus/geology-venus.png",
      rotationTime: "243 dias",
      revolutionTime: "224.7 dias",
      radius: "6.051,8 KM",
      averageTemperature: "471°C",
    },
  
    {
      planet: "Terra",
      description: "Terceiro planeta a partir do Sol e o único planeta conhecido a abrigar vida. Cerca de 29,2% da superfície da Terra é terra, com os restantes 70,8% cobertos por água. A distância da Terra ao Sol, as propriedades físicas e a história geológica permitiram que a vida evoluísse e prosperasse.",
      source: "https://pt.wikipedia.org/wiki/Terra",
      overview: "images/earth/planet-earth.svg",
      internalStructure: "images/earth/planet-earth-internal.svg",
      surfaceGeology: "images/earth/geology-earth.png",
      rotationTime: "0.99 dias",
      revolutionTime: "365.26 dias",
      radius: "6.371 KM",
      averageTemperature: "16°C",
    },
  
    {
      planet: "Marte",
      description: "Marte é o quarto planeta a partir do Sol e o segundo menor planeta do Sistema Solar, sendo maior que apenas Mercúrio. Em inglês, Marte carrega o nome do deus romano da guerra e é muitas vezes referido como o 'Planeta Vermelho'.",
      source: "https://pt.wikipedia.org/wiki/Marte_(planeta)",
      overview: "images/mars/planet-mars.svg",
      internalStructure: "images/mars/planet-mars-internal.svg",
      surfaceGeology: "images/mars/geology-mars.png",
      rotationTime: "1.03 dias",
      revolutionTime: "1.88 anos",
      radius: "3.389,5 KM",
      averageTemperature: "-28°C",
    },
  
    {
      planet: "Júpiter",
      description: "Júpiter é o quinto planeta a partir do Sol e o maior do Sistema Solar. É um gigante gasoso com uma massa duas vezes e meia maior que a de todos os outros planetas do Sistema Solar combinados, mas menos de um milésimo da massa do Sol.",
      source: "https://pt.wikipedia.org/wiki/J%C3%BApiter_(planeta)",
      overview: "images/jupiter/planet-jupiter.svg",
      internalStructure: "images/jupiter/planet-jupiter-internal.svg",
      surfaceGeology: "images/jupiter/geology-jupiter.png",
      rotationTime: "9.93 horas",
      revolutionTime: "11.86 anos",
      radius: "69.911 KM",
      averageTemperature: "-108°C",
    },
  
    {
      planet: "Saturno",
      description: "Saturno é o sexto planeta a partir do Sol e o segundo maior do Sistema Solar, depois de Júpiter. É um gigante gasoso com um raio médio de cerca de nove vezes e meia o da Terra. Tem apenas um oitavo da densidade média da Terra.",
      source: "https://pt.wikipedia.org/wiki/Saturno_(planeta)",
      overview: "images/saturn/planet-saturn.svg",
      internalStructure: "images/saturn/planet-saturn-internal.svg",
      surfaceGeology: "images/saturn/geology-saturn.png",
      rotationTime: "10.8 horas",
      revolutionTime: "29.46 anos",
      radius: "58.232 KM",
      averageTemperature: "-138°C",
    },
  
    {
      planet: "Urano",
      description: "Urano é o sétimo planeta a partir do Sol. Seu nome é uma referência ao deus grego do céu, Urano segundo a mitologia grega, era o bisavô de Ares. Tem o terceiro maior raio planetário e a quarta maior massa planetária do Sistema Solar.",
      source: "https://pt.wikipedia.org/wiki/Urano_(planeta)",
      overview: "images/uranus/planet-uranus.svg",
      internalStructure: "images/uranus/planet-uranus-internal.svg",
      surfaceGeology: "images/uranus/geology-uranus.png",
      rotationTime: "17.2 horas",
      revolutionTime: "84 anos",
      radius: "25.362 km",
      averageTemperature: "-195°C",
    },
  
    {
      planet: "Netuno",
      description: "Netuno é o oitavo e mais distante planeta solar conhecido do Sol. No Sistema Solar, é o quarto maior planeta em diâmetro, o terceiro planeta mais massivo e o planeta gigante mais denso. É 17 vezes a massa da Terra, mais massiva que seu quase gêmeo Urano.",
      source: "https://pt.wikipedia.org/wiki/Netuno_(planeta)",
      overview: "images/neptune/planet-neptune.svg",
      internalStructure: "images/neptune/planet-neptune-internal.svg",
      surfaceGeology: "images/neptune/geology-neptune.png",
      rotationTime: "16.08 horas",
      revolutionTime: "164.79 anos",
      radius: "24.622 KM",
      averageTemperature: "-201°C",
    },
  ];